services:
  nats-jetstream:
    image: "nats:2.3.2-alpine"
    command:
      - "--port"
      - "4222"
      - "--http_port"
      - "8222"
      - "--jetstream"
      - "--store_dir"
      - "/data"
      - "--debug"
    ports:
      - "4222:4222"
      - "8222:8222"
    volumes:
      - ".docker-data/nats-jet-stream:/data"
